### ISSUE TITLE
投稿時にチームを選択して投稿できるようにしたい

### ISSUE THREAD

**Issue by masamitsu-konya** [Atrae/memoru#47]
投稿時に一体どのチームに投稿されるかがわからなかったので、わかるようにしたい。

改善案としては
1, ヘッダーにチーム選択のセレクトボックスを移動させる
2, 投稿時にチームを選択できるようにする
の2案考えたが、
1のヘッダーにチーム選択ボックスを持っていった場合、
記事編集中にヘッダーのセレクトボックスを変えられてしまった場合に、
記事内容が破棄されてしまうという不安が発生するため、
2にした。

見た目は以下のようになる。
![2015-04-03 15 31 56](https://cloud.githubusercontent.com/assets/1867291/6978959/fca291b6-da16-11e4-908c-65444fc68bf7.png)

フロント側は実装済。

システム対応求む。

**Comment by ysk1031** [comment]
@masamitsu-konya 

実装してみました。
紺谷さんの理想イメージと違うかもしれないので、お暇な時に手元で動かしてご確認くだされー:bow:
fix-47ってブランチにpushしてあります。
https://github.com/Atrae/memoru/pull/48

- 既に作成済みのノートの投稿チームを変えるのはちょっと変かな？と思って、投稿先を選べるのは新規作成時に限定してます
- ボタンの文言を勝手に変えました...

**Comment by masamitsu-konya** [comment]
@ysk1031 
すげくいいね！
マージしちゃいます！

**Comment by ysk1031** [comment]
@masamitsu-konya わーい:blush:
