### ISSUE TITLE
編集時に画像をアップロードできるようにして欲しい

### ISSUE THREAD

**Issue by masamitsu-konya** [Atrae/memoru#51]
@ysk1031 
デザイナー陣で、思考ログをmemoruで取っていこうという風に決めました。
で、画像のアップロードができないとデザイナーはちょっと厳しいので優先的にやっていただけると助かります。

**Comment by ysk1031** [comment]
@masamitsu-konya 
「アップロード」ボタン押したら画像アップロードされるようにはなりました！
（アップロードボタンのデザインが変になるのはJSのライブラリのせいだと思うので、もう少し調べます

あと、ドラッグ&ドロップでもアップロードされるんですが、
JSがバグってて変な文字列が入っちゃうんで直します

**Comment by masamitsu-konya** [comment]
@ysk1031 
Great!!

**Comment by ysk1031** [comment]
@masamitsu-konya ボタンおかしくなるのもCSSで無理やり消したんでクローズします。

画像あると、Markdownのプレビューのカクカク感がすごく気になるので、今月中に何とかします。。
